name: braval
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^7.0.0
  braval_ui:
    path: packages/braval_ui
  calendar_repository:
    path: packages/calendar_repository
  equatable: ^2.0.0
  firebase_core: ^1.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_localizations:
    sdk: flutter
  flutter_speed_dial: ^4.2.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.0
  intl: ^0.17.0
  profile_repository:
    path: packages/profile_repository
  team_repository:
    path: packages/team_repository
  very_good_analysis: ^2.1.0

dev_dependencies:
  bloc_test: ^8.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0

flutter:
  uses-material-design: true
  generate: true
