name: braval_ui
description: UI Toolkit for the Braval Flutter Application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  calendar_repository:
    path: ../calendar_repository
  firebase_image: ^1.0.1
  flutter:
    sdk: flutter
  profile_repository:
    path: ../profile_repository
  table_calendar: ^3.0.2
  very_good_analysis: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
          weight: 400
        - asset: assets/fonts/ProximaNova-Bold.otf
          weight: 700
  assets:
    - assets/img/study.png
    - assets/img/football.png
    - assets/img/basket.png
